### ISSUE TITLE
Timer doesn't exist anymore

### ISSUE THREAD

**Issue by itsamedood** [Dharmey747/vscode-timer#1]
I've been using this extension for a while now, easily over a year. All of a sudden, I noticed the timer vanished. I tried uninstalling and reinstalling. Also no, it wasn't hidden from the status bar, I right-clicked and checked. I did also try resetting the timer, but a pop-up window came up saying `Command 'Reset Timer' resulted in an error (command 'timer.resetTimer' not found)`.

**\*** It's also worth noting I am running macOS, so I don't know if this issue is also present on Windows or Linux.
<div align="center">
<img width="254" alt="Screenshot 2022-11-24 at 10 38 50" src="https://user-images.githubusercontent.com/74739472/203822439-7dd29750-35c7-464c-a8a4-1ea277bce24d.png">
</div>

**Comment by Dharmey747** [comment]
Hey!
I've tried to execute the command on both of my machines (running Windows 11 & macOS Ventura) and they both worked with no issues. Could you try to maybe install the previous version to see if that helps?

**Comment by itsamedood** [comment]
I installed version `1.1.0` and it works now, I'm embarrassed I hadn't thought to do that 😅

Thank you!
