### ISSUE TITLE
Analytics does not show full date

### ISSUE THREAD

**Issue by madaomax** [Dharmey747/vscode-timer#2]
In Analytics, the day of the date will always only show the last digit. 
![image](https://github.com/Dharmey747/vscode-timer/assets/41228003/1da34cf6-ffa3-4e85-bd23-776141ed1721)

**Comment by Dharmey747** [comment]
Hi and thank you for your bug report!

The issue has now been fixed, and I've pushed version `2.0.1` which contains the fix.
Please keep in mind that the fix will only affect the data after the update, so unfortunately the timestamps prior will remain bugged.
